# -*- coding: utf-8 -*-
"""normal and abnormal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HhsrBZ561hVdtC5zlwKQ0it6N9IXymbE
"""

# ECG SIGNAL CLASSIFICATION USING DNN

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

# 1. LOAD DATASET
from google.colab import files
uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

data = pd.read_csv(file_name, header=None)

print("Dataset Loaded Successfully!")
print("Shape of dataset:", data.shape)


# 2. PREPROCESSING
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

# Remove NaN labels
mask = ~np.isnan(y)
X = X[mask]
y = y[mask]

# Convert to binary
y = np.where(y == 0, 0, 1)

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Preprocessing Completed!")
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)


# 3. BUILD DNN MODEL
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(2, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',   # ✅ FIXED
    metrics=['accuracy']
)

model.summary()


# 4. TRAIN MODEL
history = model.fit(
    X_train, y_train,
    epochs=25,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)


# 5. TEST EVALUATION
loss, accuracy = model.evaluate(X_test, y_test)
print("\nTest Accuracy: {:.2f}%".format(accuracy * 100))


# 6. ANALYSIS FUNCTION (WITH BORDERLINE)
def analyze_dataset():

    print("\n====================================")
    print("ANALYZING DATASET")
    print("====================================")

    predictions = model.predict(X_test)

    pred_classes = np.argmax(predictions, axis=1)
    confidence = np.max(predictions, axis=1)

    borderline_mask = confidence < 0.60

    final_predictions = []

    for i in range(len(pred_classes)):
        if borderline_mask[i]:
            final_predictions.append(2)
        else:
            final_predictions.append(pred_classes[i])

    final_predictions = np.array(final_predictions)

    total = len(final_predictions)

    normal_count = np.sum(final_predictions == 0)
    abnormal_count = np.sum(final_predictions == 1)
    borderline_count = np.sum(final_predictions == 2)

    normal_percentage = (normal_count / total) * 100
    abnormal_percentage = (abnormal_count / total) * 100
    borderline_percentage = (borderline_count / total) * 100

    print("Total Samples:", total)
    print("Normal ECG: {:.2f}%".format(normal_percentage))
    print("Abnormal ECG: {:.2f}%".format(abnormal_percentage))
    print("Borderline ECG: {:.2f}%".format(borderline_percentage))

    # Bar graph
    categories = ["Abnormal ECG", "Normal ECG", "Borderline ECG"]
    values = [abnormal_percentage, normal_percentage, borderline_percentage]

    plt.figure()
    plt.bar(categories, values)
    plt.xlabel("ECG Categories")
    plt.ylabel("Percentage (%)")
    plt.title("ECG Classification Distribution")
    plt.xticks(rotation=15)
    plt.show()


    # CONFUSION MATRIX (3x3)
    y_true_3class = []

    for val in y_test:
        if val == 0:
            y_true_3class.append(0)   # Normal
        else:
            y_true_3class.append(1)   # Abnormal

    y_true_3class = np.array(y_true_3class)

    # final_predictions already contains:
    # 0 = Normal
    # 1 = Abnormal
    # 2 = Borderline

    cm = confusion_matrix(
        y_true_3class,
        final_predictions,
        labels=[0, 2, 1]   # Normal, Borderline, Abnormal
    )

    plt.figure(figsize=(6,5))
    sns.heatmap(cm,
                annot=True,
                fmt='d',
                cmap='Reds',
                xticklabels=["Normal", "Borderline", "Abnormal"],
                yticklabels=["Normal", "Borderline", "Abnormal"])

    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title("Confusion Matrix")
    plt.show()

    print("\nTotal Samples:", total)
    print("Normal ECG Beats: {} ({:.2f}%)".format(normal_count, normal_percentage))
    print("Abnormal ECG Beats: {} ({:.2f}%)".format(abnormal_count, abnormal_percentage))

    if normal_percentage == 100:
        print("\nFinal Result: DATASET CONTAINS ONLY NORMAL ECG")
    elif abnormal_percentage == 100:
        print("\nFinal Result: DATASET CONTAINS ONLY ABNORMAL ECG")
    else:
        print("\nFinal Result: MIXED ECG DATASET")

    print("\n====================================\n")



# 7. TRAINING GRAPH
plt.figure()
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Train", "Validation"])
plt.show()


# 8. RUN ANALYSIS
analyze_dataset()

print("\nOriginal Label Distribution:")
print(pd.Series(y).value_counts())